### ISSUE TITLE
Main page, view all research posts

### ISSUE THREAD

**Issue by KyanPepper** [WSU-CptS-322-Fall-2023/termproject-teamgit#4]
| Use case # 2    |   |
| ------------------ |--|
| Name              | "Main page, view all research posts"  |
| Users             | "Students & Faculty"  |
| Rationale         | "view all open Research Posts"  |
| Triggers          | "clicking a link to the post description"  |
| Preconditions     | "Being a wsu student or faculty, posts are loaded in"  |
| Actions           | "clicking on the post"  |
| Alternative paths | "return back to main page or go back to main page"  |
| Postconditions    | "Research Post description page"  |
| Acceptance tests  | "url link works"  |
| Iteration         | "Iteration 1"  |

**Comment by Fredyfox21** [comment]
update use case for this issue

**Comment by KyanPepper** [comment]
Good
